# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb81b99ffcac1b4e22a6641e8046d822cd11ce384ee6bca4bd47eaa8ebd01d2675e5bfda2dff067086dbc2c5073f21cfc75ee277279d649bef748eea3d55cba1

test:
  secret_key_base: 2591851eb1830f17d1ed77da23f2188edc1ed3cf04e54533a73034b25f1e61141cf51be90f19d6dddd8a85ee5a085d6c03d2e603590c00fae87f7ab057c1ecab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
